##### Site settings
title: Darth CAV's Home Page
description: > # Darth CAV's web site.
copyright: © 2015 DARTH CAV
url: https://darthcav.github.io # base url of your site, default: {{ site.github.url }}
exclude: [ "README.md", "LICENSE" ]
timezone: Europe/Berlin
author:
  name: Darth CAV

##### GitHub configuration
markdown: redcarpet # better than "kramdown"
highlighter: pygments # pygments or (unsupported in GitHub) rouge
repository: darthcav/darthcav.github.io
gems:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - rouge
paginate: 10
permalink: /blog/:year/:month/:day/:title.html

##### RedCarpet configuration
redcarpet:
  extensions: [ "smart" ]

##### Twitter configuration
twitter:
  user: darthcav
  url: https://twitter.com/darthcav

##### Scripts configuration
scripts:
  bootstrap: https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js
  jquery: https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js
  twitter: https://darthcav.github.io/scripts/twitter.js
