##### Site settings
title: Darth CAV's Home Page
description: > # Darth CAV's web site.
copyright: © 2015&#8212;2016 DARTH CAV
# url: https://darthcav.github.io # base url of your site, default: {{ site.github.url }}
exclude: [ "README.md", "LICENSE" ]
timezone: Europe/Berlin
author:
  name: Darth CAV

##### GitHub configuration
markdown: kramdown
highlighter: rouge # pygments | (unsupported in GitHub) rouge
repository: darthcav/darthcav.github.io
gems:
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - rouge
paginate: 10
permalink: /blog/:year/:month/:day/:title.html

##### Kramdown configuration
kramdown:
  input: GFM

##### Twitter configuration
twitter:
  user: darthcav
  url: https://twitter.com/darthcav

##### Scripts configuration
scripts:
  bootstrap: https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js
  ga: https://darthcav.github.io/scripts/ga.js
  jquery: https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js
  mathjax: https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  tether: https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js
  twitter: https://darthcav.github.io/scripts/twitter.js
  customize-md: https://darthcav.github.io/scripts/customize-md.js
